---
title: "Analysis plan"
# date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    highlight: tango
    code_folding: hide
params:
  author: "Ben Jaques-Leslie"
  project_number: 2312
  project_name: "Occupancy Patterns"
  google_drive_home: "G:/Shared drives/GSA Evaluation Division/Projects/1.0 Real Estate Solutions (LQ1)/2312 Work Patterns"
  data_folder_1: "prepared-data"
  data_file_1: "clusters-employee-2023-09-06.rdata"
  data_file_2: "prep_employees_2023-09-06.rdata"
  in_number_of_clusters_1: 2
  in_number_of_clusters_2: 5
  in_specification: "scale_observation_none_1_20_TRUE"
  date_cohort_month: "2022-03-01"
  observation_window_length_months: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      dpi = 300)
options(scipen=999)
tictoc::tic()
if(!("ggalluvial" %in% installed.packages()[,"Package"]))
{
  install.packages("ggalluvial")
}
if(!("arsenal" %in% installed.packages()[,"Package"]))
{
  install.packages("arsenal")
}
if(!("beepr" %in% installed.packages()[,"Package"]))
{
  install.packages("beepr")
}
if(!("geomtextpath" %in% installed.packages()[,"Package"]))
{
  install.packages("geomtextpath")
}
if(!("oesrrr" %in% installed.packages()[,"Package"]))
{
  devtools::install_github(repo = "GSA/oesrrr")
}
if(!("oescolorrrs" %in% installed.packages()[,"Package"]))
{
  devtools::install_github(repo = "GSA/oescolorrrs")
}
if(!("ggrain" %in% installed.packages()[,"Package"]))
{
  install.packages("ggrain")
}
# install.packages("tigris")
library(oesrrr)
library(tidyverse)
library(janitor)
library(skimr)
library(DataExplorer)
library(readr)
library(arsenal)
library(Hmisc)
library(readxl)
library(flextable)
library(ggthemes)
library(tidymodels)
library(patchwork)
library(sf)
library(tigris)
library(ggrepel)
library(ggalluvial)
library(ggrain)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
```

```{r include=FALSE}
load(file = file.path(params$google_drive_home,"03. Data Collection",params$data_folder_1,params$data_file_1))
```

```{r include=FALSE}
load(file = file.path(params$google_drive_home,"03. Data Collection",params$data_folder_1,params$data_file_2))
```

```{r include=FALSE}
clust_1 <- 
  kclusts %>% 
  filter(
    k == params$in_number_of_clusters_1 &
      specification == params$in_specification
  )
```

```{r include=FALSE}
clust_2 <- 
  kclusts %>% 
  filter(
    k == params$in_number_of_clusters_2 &
      specification == params$in_specification
  )
```

```{r include=FALSE}
clusters_1 <- 
  clust_1 %>%
  unnest(cols = c(tidied))

assignments_1 <- 
  clust_1 %>% 
  unnest(cols = c(augmented))

clusterings_1 <- 
  clust_1 %>%
  unnest(cols = c(glanced))

```

```{r include=FALSE}
clusters_2 <- 
  clust_2 %>%
  unnest(cols = c(tidied))

assignments_2 <- 
  clust_2 %>% 
  unnest(cols = c(augmented))

clusterings_2 <- 
  clust_2 %>%
  unnest(cols = c(glanced))

```

```{r include=FALSE}
rename_to_k <- function(in_data)
{
  tot_cluster <- in_data %>% select(k) %>% distinct() %>% pull()
  out_data <-
    in_data %>% rename_with( ~ glue::glue("{.x}_{tot_cluster}"), .cluster)
  return(out_data)
}
```

```{r include=FALSE}
assignments <-
  assignments_1 %>%
  rename_to_k() %>%
  select(person_id, starts_with(".cluster")) %>%
  full_join(assignments_2 %>%
              rename_to_k() %>%
              select(person_id, starts_with(".cluster")))
```

```{r include=FALSE}
d <-
  assignments %>%
  select(person_id, starts_with(".cluster")) %>%
  full_join(prep_employees) %>% 
  mutate(
    across(
      .cols = starts_with(".cluster"),
      .fns = ~fct_na_value_to_level(., level = "(Missing)")
    )
  )
```

```{r include=FALSE}
d <- d %>% 
  mutate(
    .cluster_5 = fct_recode(.cluster_5,
                            "Telecommuters" = "1",
                            "Office visitors" = "2",
                            "Hybrid workers" = "3",
                            "Disconnected workers" = "4",
                            "In-office workers" = "5"),
    .cluster_5 = fct_relabel(.cluster_5, ~str_wrap(.x,width = 10))
  )
```

```{r}
d %>% 
  skim()
```

```{r}
d %>% 
  group_by(.cluster_5) %>% 
  skim(daily_status_reporting_to_job_site,
       daily_status_reporting_to_job_site_observation_prop,
       daily_status_teleworking,
       daily_status_teleworking_observation_prop,
       days_colocated_1,
       days_colocated_1_observation_prop,
       days_colocated_supervisor,
       days_colocated_supervisor_observation_prop,
       days_colocated_team,
       days_colocated_team_observation_prop,
       days_telework_team,
       days_telework_team_observation_prop,
       working_days,
       team_size_mode) %>% 
  as.data.frame()
```


# Table data

## Percent of GSA employees

```{r}
prep_d_01 <- 
  d %>%
  group_by(.cluster_5) %>% 
  count() %>% 
  ungroup()
 
prep_d_02 <- 
  prep_d_01 %>% 
  mutate(tot = d %>% count() %>% pull(),
         prop = n/tot,
         text = scales::percent(prop, accuracy = .1))

prep_d_02
```

## Days per pay period

```{r}
date_cohort_month_start <- ymd(params$date_cohort_month)
date_cohort_month_end <- ceiling_date(date_cohort_month_start,unit = "month") %>% rollbackward()
date_observation_window_month_start <- date_cohort_month_start %m+% months(params$observation_window_length_months)
date_observation_window_month_end <- 
  # ceiling_date(date_observation_window_month_start,unit = "month") %>% 
  date_observation_window_month_start %>% 
  rollbackward()
```


```{r}
prep_a <- 
  tibble(
  date = seq.Date(from = ymd("2022-01-01"),
         to = ymd("2022-12-31"),
         by = "2 weeks")
) %>% 
  rownames_to_column(var = "period_number") 
```

Review data.

```{r}
prep_a %>% 
  skim()
```

```{r}
params$date_cohort_month %m+% months(params$observation_window_length_months)
```


Second, create a dataframe of all the days of the year.

```{r}
prep_b <- 
  tibble(
  date = seq.Date(from = ymd("2022-01-01"),
         to = ymd("2022-12-31"),
         by = "days")
)
```

Review data.

```{r}
prep_b %>% 
  skim()
```

# Clusters and position categories (alluvial)

```{r}
prep_d_01 <- 
  d %>% 
  group_by(position_category_description) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n))

prep_v_01 <- 
  prep_d_01 %>% 
  slice(3) %>% 
  pull(n)

prep_d_02 <-
  d %>%
  mutate(position_category_description = fct_lump_min(position_category_description, min = prep_v_01),
         position_category_description = fct_infreq(position_category_description)) %>%
  group_by(position_category_description,.cluster_5) %>%
  count() %>%
  ungroup() %>%
  arrange(desc(n)) %>% 
  rename(num = n) %>% 
  mutate(
    position_category_description = fct_relevel(position_category_description, 
                                               "Offsite",
                                               "Onsite Flexible",
                                               "Onsite Required",
                                               "Other")
  )

prep_d_03 <- 
  prep_d_02 %>% 
  filter(position_category_description != "Other")

prep_d_04 <- 
  d %>% 
  group_by(.cluster_5) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  rename(tot = n)

prep_d_05 <- 
  prep_d_03 %>% 
  full_join(prep_d_04) %>% 
  mutate(
    n = num/tot,
    text = scales::comma(num)
  ) 
```

```{r}
is_alluvia_form(prep_d_05)
```

```{r}
p_1 <- 
  prep_d_05 %>% 
  mutate(.cluster_5 = fct_relabel(.cluster_5,~str_wrap(.,width = 50))) %>% 
  ggplot(aes(y = num, axis1 = .cluster_5, axis2 = position_category_description, fill = .cluster_5)) +
  geom_alluvium(width = 1/12) +
  geom_stratum(width = 1/12,
               # alpha = 1,
               fill = "black",
               color = "white"
               ) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum)),
             fill = "white",
             # , alpha = .05,
             hjust = "inward"
             ) +
  ylab("Number of employees") +
  scale_y_continuous(labels = scales::comma) +
  oescolorrrs::scale_fill_oes() +
  oescolorrrs::scale_color_oes() +
  theme_light() +
  theme(
    legend.position = "None",
    axis.title.x = element_blank(),
    axis.text.x = element_blank())
```


```{r}
p_1
```

```{r}
p_2 <- 
  prep_d_05 %>% 
  mutate(.cluster_5 = fct_relabel(.cluster_5,~str_wrap(.,width = 50))) %>% 
  ggplot(aes(y = num, axis1 = position_category_description, axis2 = .cluster_5, fill = .cluster_5)) +
  geom_alluvium(width = 1/12) +
  geom_stratum(width = 1/12,
               # alpha = 1,
               fill = "black",
               color = "white"
               ) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum)),
             fill = "white",
             # , alpha = .05,
              size = 2,
             hjust = "inward"
             ) +
  labs(title = "Linking position categories to work pattern groups") +
  ylab("Number of employees") +
  scale_y_continuous(labels = scales::comma) +
  oescolorrrs::scale_fill_oes() +
  oescolorrrs::scale_color_oes() +
  theme_light() +
  theme(
    legend.position = "None",
    axis.title.y = element_text(size = 8),
    axis.title.x = element_blank(),
    axis.text.x = element_blank())
```

```{r}
p_2
```


```{r}
file_name <- "abstract_2.png"
fp <- file.path(params$google_drive_home,"04. Analysis", "output", "png",file_name)
```


```{r}
ggsave(filename = fp, plot = p_2, width = 6, height = 3, units = "in")
```